name: Minimal Manual Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Read org secret
        run: echo "Secret is ${{ secrets.MY_SECRET }}"
      - name: Read org variable
        run: echo "Org variable is ${{ vars.EXAMPLE }}"
